name: Fly Deploy

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set Fly.io secrets
        run: |
          flyctl secrets set SECRET=${{ secrets.SECRET }}
          flyctl secrets set API_TOKEN=${{ secrets.API_TOKEN }}
          flyctl secrets set CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
          flyctl secrets set API_BASE_URL=${{ secrets.API_BASE_URL }}
          flyctl secrets set DATABASE_URL=${{ secrets.DATABASE_URL }}
          flyctl secrets set UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}
          flyctl secrets set UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
