name: Test Rest API
on:
  push:
    branches:
      - main

env:
  SECRET: ${{secrets.SECRET}}
  API_TOKEN: ${{secrets.API_TOKEN}}
  CORS_ORIGIN: ${{secrets.CORS_ORIGIN}}
  API_BASE_URL: ${{secrets.API_BASE_URL}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  UPSTASH_REDIS_REST_URL: ${{secrets.UPSTASH_REDIS_REST_URL}}
  UPSTASH_REDIS_REST_TOKEN: ${{secrets.UPSTASH_REDIS_REST_TOKEN}}

jobs:
  test:
    name: Testing API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ci

      - name: Run tests
        run: bun test
