name: Test Rest API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  API_BASE_URL: ${{secrets.API_BASE_URL}}
  API_TOKEN: ${{secrets.API_TOKEN}}
  UPSTASH_REDIS_REST_URL: ${{secrets.UPSTASH_REDIS_REST_URL}}
  UPSTASH_REDIS_REST_TOKEN: ${{secrets.UPSTASH_REDIS_REST_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test
